version: "3"

services:
  finding-out-chess-pieces-moves-backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py 0.0.0.0:8000"
  